### ISSUE TITLE
FalsePattern and GTNH Series of dependent mods now incompatible

### ISSUE THREAD

**Issue by MysteriousSheep** [GTNewHorizons/GTNHMixins#1]
The newer [GTNH](https://github.com/GTNewHorizons) dependent mods are now requiring [GTNHMixins](https://github.com/GTNewHorizons/GTNHMixins) which will not load with [GasStation](https://github.com/FalsePattern/GasStation)

The newer [FalsePattern](https://github.com/FalsePattern) dependent mods are now requiring [GasStation](https://github.com/FalsePattern/GasStation) which will not load with [GTNHMixins](https://github.com/GTNewHorizons/GTNHMixins)

Unfortunately, neither series of mods work with just one or the other.

Both files conflict as being a duplicate mod "spongemixins"

![image](https://user-images.githubusercontent.com/115964468/196079588-c158bc88-4fd3-4642-a46e-219d606dfde3.png)

https://github.com/FalsePattern/GasStation/issues/6

**Comment by makamys** [comment]
None of FalsePattern's mods actually depend on GasStation at the moment as far as I know. You should be able to run them with GTNHMixins (most of them with SpongeMixins even).

**Comment by mitchej123** [comment]
I can probably add some limited gas station compat, but falsepattern doesnt seem to want to collaborate or cooperate so not sure how long it will work for.

**Comment by Omgise** [comment]
> None of FalsePattern's mods actually depend on GasStation at the moment as far as I know. You should be able to run them with GTNHMixins (most of them with SpongeMixins even).

The latest version of EndlessIDs actually depend on GasStation 🤣

**Comment by makamys** [comment]
The mod does define GasStation as a dependency, but it doesn't actually use any GasStation-specific features. So defining a dummy `@Mod` annotation in GTNHMixins (similarly to what it's already doing for SpongeMixins) should do the trick.

**Comment by makamys** [comment]
In FalsePatternLib 0.10.14, GasStation's integrity check [was made stricter](https://github.com/FalsePattern/FalsePatternLib/commit/4cbda7a568cb5b0fe86f7159d57c890cc497250b), so this solution no longer works unfortunately.

**Comment by mitchej123** [comment]
Not playing these games. If he wants to be immature and make things intentionally incompatible then he can do so.

**Comment by makamys** [comment]
I created [a stripped down version of GTNHMixins](https://github.com/makamys/GTNHMixinsLite) that can be used alongside GasStation (and theoretically, any other 0.8.5 Mixin bootstrap mod).

Using it, I was able to run EndlessIDs, FalseTweaks, Hodgepodge, BoP, and the latest FPLib together without any apparent issues.

Hopefully this will solve it nicely for some time.
