### ISSUE TITLE
Compatibility Request: Gasstation

### ISSUE THREAD

**Issue by branman5949** [GTNewHorizons/GTNHMixins#10]
is there a way for this mod to be run with Falsepattern's Gasstation mixins?
https://github.com/FalsePattern/GasStation

**Comment by makamys** [comment]
No, you can only run a single mixin bootstrap mod at a time as a general rule. At this time GTNHMixins has enough compat code for GasStation that it can be used in place of it, as long as you make sure you don't update FalsePatternLib past 0.10.13. (See #1.) A different solution may be necessary soon, though.

**Comment by mitchej123** [comment]
He is going out of the way to make things incompatible. I'm not playing those immature games.

**Comment by mitchej123** [comment]
Also sorry. I'd love for things to be compatible and for everyone to play nicely.  Some people have other ideas.
