### ISSUE TITLE
Incompatibility with mods that embed Mixin

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/GTNHMixins#2]
> (This was already discussed, just posting it as a reminder and public documentation.)

FML loads coremods in alphabetical order by jar name, so if a mod embeds a different version of Mixin and has a jar name that comes before GTNHMixins, its version of Mixin will be loaded, causing compatibility mayhem.

Here's how other Mixin bootstrap mods solved the issue:
* [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files) prefaces jar names with a `!`
* [MixinBootstrapLegacy](https://www.curseforge.com/minecraft/mc-mods/mixinbootstraplegacy/files) prefaces jar names with a `!`
* [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap/files) prefaces jar names with a `_`
* [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility/files) prefaces jar names with `[___`
* [GasStation](https://github.com/FalsePattern/GasStation) prefaces jar names with `00`

GitHub strips `!` from jar names in releases, so that should be kept in mind.

**Comment by boubou19** [comment]
that's so hacky...

**Comment by mitchej123** [comment]
thx forge

**Comment by serenibyss** [comment]
Closing as this repo is archived
