### ISSUE TITLE
Incompatibility with CoreTweaks

### ISSUE THREAD

**Issue by Midnight145** [GTNewHorizons/GTNHMixins#20]
[CoreTweaks](https://github.com/makamys/CoreTweaks/releases/tag/0.3.0.1)

I get a crash on launch, no matter if I have GTNHMixins loaded first via renaming to 00gtnhmixins-2.1.13.jar

Tried with both coretweaks and coretweaks+nomixin

Logfile with GTNHMixins loaded first, or with coretweaks+nomixin: https://mclo.gs/S2ai3U6

Logfile with GTNHMixins loaded second: https://mclo.gs/mwAQkE5

Thank you!

**Comment by makamys** [comment]
Adding [Mixingasm](https://github.com/makamys/Mixingasm) could be worth a try.

**Comment by Midnight145** [comment]
Mixingasm and coretweaks+nomixin works, thank you!
