### ISSUE TITLE
Look into forcing  IEarlyMixinLoader classes to load without requiring IFMLLoadingPlugin

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GTNHMixins#3]
Currently both  `IEarlyMixinLoader` and `IFMLLoadingPlugin` are required to ensure the mod is loaded at the correct stage.  Look into identifying `IEarlyMixinLoader` classes without the coremod plugin.

**Comment by mitchej123** [comment]
Might be required to be done in `SpongePoweredMixins` given they're already looking for `IMixinConfigPlugin` ....

**Comment by serenibyss** [comment]
Closing as this repo is archived
